# Generated by Django 6.0.3 on 2026-03-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_oil_company'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', error_messages={'invalid': 'Введите корректную информацию о себе.'}, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='', error_messages={'blank': 'Укажите отдел.', 'invalid': 'Введите корректное название отдела.'}, max_length=150, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='oil_company',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'Выберите нефтяную компанию.', 'invalid': 'Выберите корректную нефтяную компанию.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.oilcompany', verbose_name='Нефтяная компания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', error_messages={'blank': 'Укажите номер телефона.', 'invalid': 'Введите корректный номер телефона.'}, max_length=30, verbose_name='Телефон'),
        ),
    ]
