# Generated by Django 6.0.3 on 2026-03-26 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_bio_alter_profile_department_and_more'),
        ('companies', '0002_alter_oilcompany_options_alter_oilcompany_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, error_messages={'invalid': 'Введите корректную информацию о себе.'}, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(error_messages={'blank': 'Укажите отдел.', 'invalid': 'Введите корректное название отдела.'}, max_length=150, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='oil_company',
            field=models.ForeignKey(error_messages={'blank': 'Выберите нефтяную компанию.', 'invalid': 'Выберите корректную нефтяную компанию.'}, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.oilcompany', verbose_name='Нефтяная компания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(error_messages={'blank': 'Укажите номер телефона.', 'invalid': 'Введите корректный номер телефона.'}, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
