# Generated by Django 6.0.3 on 2026-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oilcompany',
            options={'ordering': ['name'], 'verbose_name': 'Нефтяная компания', 'verbose_name_plural': 'Нефтяные компании'},
        ),
        migrations.AlterField(
            model_name='oilcompany',
            name='name',
            field=models.CharField(help_text='Уникальное название нефтяной компании', max_length=255, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='oilcompany',
            name='region',
            field=models.CharField(help_text='Регион деятельности компании', max_length=255, verbose_name='Регион'),
        ),
    ]
