# Generated by Django 6.0.3 on 2026-03-19 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('work_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Время работы, часов')),
                ('liquid_debit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дебит жидкости, м³/сут')),
                ('water_cut', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Обводненность, %')),
                ('oil_density', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Плотность нефти, т/м³')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_productions', to='productions.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Суточный рапорт',
                'verbose_name_plural': 'Суточные рапорты',
                'constraints': [models.UniqueConstraint(fields=('well', 'date'), name='unique_daily_production_per_well_date')],
            },
        ),
    ]
