# Generated by Django 6.0.3 on 2026-03-19 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_dailyproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='water_cut',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Обводненность, %'),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='work_time',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Время работы, часов'),
        ),
    ]
