# Generated by Django 6.0.3 on 2026-03-20 04:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('productions', '0003_alter_dailyproduction_water_cut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, error_messages={'invalid': 'Введите корректное значение широты.'}, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='well',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, error_messages={'invalid': 'Введите корректное значение долготы.'}, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='well',
            name='max_drilling_depth',
            field=models.PositiveIntegerField(blank=True, error_messages={'invalid': 'Введите корректную максимальную глубину бурения.'}, null=True, verbose_name='Максимальная глубина бурения, м'),
        ),
        migrations.AddField(
            model_name='well',
            name='oil_company',
            field=models.ForeignKey(blank=True, error_messages={'blank': 'Выберите нефтяную компанию.'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='companies.oilcompany', verbose_name='Нефтяная компания'),
        ),
        migrations.AddField(
            model_name='well',
            name='type',
            field=models.CharField(blank=True, default='', error_messages={'blank': 'Укажите тип скважины.'}, max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='date',
            field=models.DateField(error_messages={'blank': 'Укажите дату.', 'invalid': 'Введите корректную дату.'}, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='liquid_debit',
            field=models.DecimalField(decimal_places=2, error_messages={'blank': 'Укажите дебит жидкости.', 'invalid': 'Введите корректное значение дебита жидкости.'}, max_digits=10, verbose_name='Дебит жидкости, м³/сут'),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='oil_density',
            field=models.DecimalField(decimal_places=3, error_messages={'blank': 'Укажите плотность нефти.', 'invalid': 'Введите корректное значение плотности нефти.'}, max_digits=5, verbose_name='Плотность нефти, т/м³'),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='water_cut',
            field=models.DecimalField(decimal_places=2, error_messages={'blank': 'Укажите обводненность.', 'invalid': 'Введите корректное значение обводненности.'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Обводненность не может быть меньше 0%.'), django.core.validators.MaxValueValidator(100, message='Обводненность не может быть больше 100%.')], verbose_name='Обводненность, %'),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='work_time',
            field=models.DecimalField(decimal_places=2, error_messages={'blank': 'Укажите время работы.', 'invalid': 'Введите корректное число часов.'}, max_digits=4, validators=[django.core.validators.MinValueValidator(0, message='Время работы не может быть меньше 0 часов.'), django.core.validators.MaxValueValidator(24, message='Время работы не может быть больше 24 часов.')], verbose_name='Время работы, часов'),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(error_messages={'blank': 'Введите название скважины.', 'unique': 'Скважина с таким названием уже существует.'}, max_length=100, unique=True, verbose_name='Название скважины'),
        ),
        migrations.AlterConstraint(
            model_name='dailyproduction',
            name='unique_daily_production_per_well_date',
            constraint=models.UniqueConstraint(fields=('well', 'date'), name='unique_daily_production_per_well_date', violation_error_message='Для этой скважины уже есть запись на указанную дату.'),
        ),
    ]
