# Generated by Django 6.0.3 on 2026-03-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('productions', '0004_well_latitude_well_longitude_well_max_drilling_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='latitude',
            field=models.DecimalField(decimal_places=6, error_messages={'invalid': 'Введите корректное значение широты.'}, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='well',
            name='longitude',
            field=models.DecimalField(decimal_places=6, error_messages={'invalid': 'Введите корректное значение долготы.'}, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='well',
            name='max_drilling_depth',
            field=models.PositiveIntegerField(error_messages={'invalid': 'Введите корректную максимальную глубину бурения.'}, verbose_name='Максимальная глубина бурения, м'),
        ),
        migrations.AlterField(
            model_name='well',
            name='oil_company',
            field=models.ForeignKey(error_messages={'blank': 'Выберите нефтяную компанию.'}, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='companies.oilcompany', verbose_name='Нефтяная компания'),
        ),
        migrations.AlterField(
            model_name='well',
            name='type',
            field=models.CharField(error_messages={'blank': 'Укажите тип скважины.'}, max_length=100, verbose_name='Тип'),
        ),
    ]
