# Generated by Django 6.0.3 on 2026-04-09 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0006_alter_dailyproduction_water_cut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/daily_productions/%Y/%m/%d/', verbose_name='Excel-файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('success', 'Успешно'), ('completed_with_errors', 'Завершено с ошибками'), ('failed', 'Ошибка')], default='pending', max_length=32, verbose_name='Статус')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID Celery-задачи')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Создано записей')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено строк')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Количество ошибок')),
                ('errors_preview', models.JSONField(blank=True, default=list, verbose_name='Ошибки (превью)')),
                ('fatal_error', models.TextField(blank=True, verbose_name='Критическая ошибка')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Задача импорта суточных рапортов',
                'verbose_name_plural': 'Задачи импорта суточных рапортов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
