# Generated by Django 6.0.3 on 2026-04-10 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0008_alter_dailyproduction_water_cut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProductionExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=32, verbose_name='Статус')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID Celery-задачи')),
                ('file', models.FileField(blank=True, upload_to='exports/monthly/%Y/%m/', verbose_name='Готовый файл')),
                ('reused_cache', models.BooleanField(default=False, verbose_name='Использован кэш')),
                ('fatal_error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Задача экспорта месячного отчёта',
                'verbose_name_plural': 'Задачи экспорта месячных отчётов',
                'ordering': ['-created_at'],
            },
        ),
    ]
