# Generated by Django 6.0.3 on 2026-04-15 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0009_monthlyproductionexportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by_username', models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя (снимок)')),
                ('well_name_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Название скважины (снимок)')),
                ('report_date_snapshot', models.DateField(blank=True, null=True, verbose_name='Дата рапорта (снимок)')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], default='update', max_length=20, verbose_name='Тип действия')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Техническое имя поля')),
                ('field_verbose_name', models.CharField(blank=True, max_length=255, verbose_name='Название поля')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('message', models.TextField(blank=True, verbose_name='Текст лога')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('daily_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='productions.dailyproduction', verbose_name='Суточный рапорт')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='productions.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Журнал аудита рапортов',
                'verbose_name_plural': 'Журнал аудита рапортов',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['-changed_at'], name='productions_changed_17ec4f_idx'), models.Index(fields=['action'], name='productions_action_f0e77c_idx'), models.Index(fields=['field_name'], name='productions_field_n_6d944c_idx')],
            },
        ),
    ]
