# Generated by Django 6.0.3 on 2026-04-25 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0010_productionauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='water_cut',
            field=models.DecimalField(decimal_places=2, error_messages={'blank': 'Укажите обводненность.', 'invalid': 'Введите корректное значение обводненности.'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Обводненность не может быть меньше 0%.'), django.core.validators.MaxValueValidator(100, message='Обводненность не может быть больше 100%%.')], verbose_name='Обводненность, %'),
        ),
    ]
