# Generated by Django 6.0.3 on 2026-04-10 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('productions', '0009_monthlyproductionexportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='productions.monthlyproductionexportjob', verbose_name='Связанный экспорт'),
        ),
    ]
